language: java
jdk: openjdk7

env:
    matrix:
    - ANDROID_TARGET=android-17  ANDROID_SDKS=android-17,build-tools-17.0.0,sysimg-17 ANDROID_BUILD_TOOLS_VERSION=17.0.0 ANDROID_ABI=armeabi-v7a
 
# many of the setup fixed with information provided in
# http://rkistner.github.com/android/2013/02/05/android-builds-on-travis-ci/
before_install:
  # Install calabash for android
  - gem install calabash-android
  # Install base Android SDK
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then printf "\n\n\n\n\n" | sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  - wget http://dl.google.com/android/android-sdk_r21-linux.tgz
  - tar -zxf android-sdk_r21-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}
  # Install required Android components.
  - android update sdk --filter platform-tools,extra-android-support,$ANDROID_SDKS --no-ui --force
  - android list targets
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    
before_script:
  - chmod +x build.sh

script:
  - ./build.sh
