language: java
jdk: openjdk7


# many of the setup fixed with information provided in
# http://rkistner.github.com/android/2013/02/05/android-builds-on-travis-ci/
before_install:
  # Install base Android SDK
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then printf "\n\n\n\n\n" | sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  - wget http://dl.google.com/android/android-sdk_r21-linux.tgz
  - tar -zxf android-sdk_r21-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}
  # Install required Android components.
  - android update sdk --filter platform-tools,android-16 --no-ui --force

before_script:
  - chmod +x build.sh

script:
  - ./build.sh
